### ISSUE TITLE
Is it okay to make a copy of locations returned by your API? 

### ISSUE THREAD

**Issue by kaetemi** [e11en/pokemon-go-map#5]
Hi, I'm making my own (yet another one) locations API (will be publicly documented). Is it okay to scrape this API http://pokemon.ellenlangelaar.nl/php/getSighting.php?type=all for location data to synchronize? Trying to get the data from several different services together.

**Comment by e11en** [comment]
Hi kaetemi, 
Yeah sure as long as you do some sort of mention  to my site. Which services are you scraping as well?

**Comment by kaetemi** [comment]
Sweet, thanks. Currently also scraping pokemon-map.com.

I'm experimenting a little with geographical database queries right now, so needed some data. Doing some tests at http://pkloc.kaetemi.com/maps using a lowly populated world layer and geographical queries on the full data set when zoomed in. :)

**Comment by e11en** [comment]
@kaetemi I like the loading you do for your map, how did you manage to do that? Do you by any change have a github project about it?

**Comment by kaetemi** [comment]
I'll give you access.
